services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_localhost
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sqlserver_localhost_passwordA1*"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sqlserver_localhost_network
    volumes:
      - sqlserver_localhost_data:/var/opt/mssql

networks:
  sqlserver_localhost_network:
    name: sqlserver_localhost_network
    driver: bridge

volumes:
  sqlserver_localhost_data:
    name: sqlserver_localhost_data
    driver: local
